CREATE DATABASE IF NOT EXISTS ORGANIZACION;
USE ORGANIZACION;

CREATE TABLE IF NOT EXISTS PROYECTO (
  id_proyecto INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  presupuesto DECIMAL(12,2) NOT NULL DEFAULT 0,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS DONANTE (
  id_donante INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL,
  direccion VARCHAR(200),
  telefono VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS DONACION (
  id_donacion INT AUTO_INCREMENT PRIMARY KEY,
  monto DECIMAL(12,2) NOT NULL,
  fecha DATE NOT NULL,
  id_proyecto INT NOT NULL,
  id_donante INT NOT NULL,
  FOREIGN KEY (id_proyecto) REFERENCES PROYECTO(id_proyecto),
  FOREIGN KEY (id_donante)  REFERENCES DONANTE(id_donante)
);
